language: java
jdk:
- oraclejdk8
script:
- mvn clean
- mvn package
deploy:
  provider: releases
  api_key:
    secure: ppjCUTVh9uS7DFBE+dchGe42izxcBqWGeTa8BYALcSr6tVDDlCiYSukwfuXD/fUN3ghFhcBDIxPsFC7bWvmjwuCsUaM4iJaXN9I0NONjhEwQvDCRBtAnHnUwxwxAljdeoY4P0VO5Hj5l72u0LfTVcZc1ilck6kwnUR4Zfgf1PGbhQhHwplFQ0bpJDCHQVkVj1qhjXup+0wD101AGE8sqQYHMZFhF6kOSBfwoWn/sHT+ueTAzXtuAY96Gx7yiSn8IY1v4D01FhZUkL8fyVl5wHZhSrTfzZP4XzkEyd6ai/3fZQN6DEEN7OOxGiRemJ+L1/gpIriZOB/qqybU4Qll4jDgTT9Or9VtX24LsRXPfnQ+LAWK3HkPWAnRCKfXTJV0GjusaYZbdkxbEk6ykV+/b+Yop+E55NaXguNYtTyvHq5LnqjyXtSfe11XbKUi4gn5j72I4h28LzA9uxtHRsN2xF0oKqeErJkMxCmrT3JM2ahv8E9xSESqP2sel5ym8kSd6DGgN/n4w5u+W71ZZGAfWKRBWvAVnpprmt3iJkw9Uv5Idcipi11NFB2O1u5f/Lw47jmZ2j64e+h/PbRrUdhXyilf0Qp+gaqGh0n9z5/hLSRFItT26ZrPktZ6PcZQ1dGCSkrwB/cwHmlnGz8a5UvAPMfZ3h5osRjX+VwvkoJPuZxg=
  file: target/mc-point-locator.jar
  skip_cleanup: true
  on:
    repo: binaryoverload/mc-point-locator
    all_branches: true