name: MinecraftPointLocator
version: 1.0.4
author: BinaryOverload
main: es.esy.williamoldham.mcpointlocator.MCPointLocatorintLocator
commands:
  setpoint:
    description: Sets a point
  delpoint:
    description: Deletes a point
  point:
    description: Selects or lists a point
  locate:
    description: Teleports you to a GE to MC point